#!/bin/env -S podman build -t localhost/caddy:latest -f

# Copyright 2026, Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

ARG VERSION

FROM docker.io/library/caddy:${VERSION:+${VERSION}-}builder AS builder

ARG CADDY_DNS_LOOPIA_VERSION=de51b59f30711ad4dd2ddb1ec3c7bbe68b020646
ARG TRANSFORM_ENCODER_VERSION=ba4124974830222da7f12a091cf11ddf4d49363f

RUN --mount=type=cache,target=/go/pkg/mod                                      \
    --mount=type=cache,target=/root/.cache/go-build                            \
    xcaddy build                                                               \
    --with github.com/caddy-dns/loopia@${CADDY_DNS_LOOPIA_VERSION}             \
    --with github.com/caddyserver/transform-encoder@${TRANSFORM_ENCODER_VERSION}

FROM docker.io/library/caddy:${VERSION:-latest}

RUN apk add jq

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY rootfs/ /

# See https://caddy.community/t/caddy-docker-container-in-read-only-mode/11717/4
VOLUME /data
VOLUME /config

ENV X_CADDY_LOG_JQ=0
ENV X_CADDY_CONFIG=/etc/caddy/Caddyfile
ENV X_CADDY_CONFIG_ADAPTER=caddyfile

CMD [ "/usr/local/bin/caddy.sh" ]
