ARG VERSION

FROM docker.io/library/caddy:${VERSION:+${VERSION}-}builder AS builder

RUN xcaddy build --with github.com/caddy-dns/loopia

FROM docker.io/library/caddy:${VERSION:-latest}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
