ARG VERSION

FROM docker.io/library/caddy:${VERSION:+${VERSION}-}builder AS builder

ARG CADDY_DNS_LOOPIA_VERSION=de51b59f30711ad4dd2ddb1ec3c7bbe68b020646

RUN --mount=type=cache,target=/go/pkg/mod                                      \
    --mount=type=cache,target=/root/.cache/go-build                            \
    xcaddy build                                                               \
    --with github.com/caddy-dns/loopia@${CADDY_DNS_LOOPIA_VERSION}

FROM docker.io/library/caddy:${VERSION:-latest}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
