#!/bin/env -S podman build -t localhost/authelia:latest -f

# Copyright 2026, Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

FROM docker.io/library/alpine:3.23.5 as build

ARG VERSION=4.39.20
ARG FILE=authelia-v${VERSION}-linux-amd64-musl.tar.gz

ARG LOGFMT2JSON_GITSHA=9f00c23f68d8

RUN --mount=source=do-install,target=/usr/local/bin/do-install <<EOF
    set -eu

    do-install pk curl go
    do-install gh authelia/authelia v${VERSION} ${FILE} authelia
    do-install go github.com/mircodz/logfmt2json@${LOGFMT2JSON_GITSHA}
EOF

FROM docker.io/library/alpine:3.23.5

RUN --mount=source=do-install,target=/usr/local/bin/do-install do-install pk jq

COPY --from=build /usr/local/bin/* /usr/local/bin/
COPY rootfs/ /

# Support read-only containers
VOLUME /data/authelia

EXPOSE 9091

ENV X_AUTHELIA_CONFIG="/etc/authelia/configuration.yml"
ENV X_AUTHELIA_LOG_JQ=0
ENV X_AUTHELIA_LOG_JQ_DEBUG=0

HEALTHCHECK --interval=30s --timeout=3s --start-period=1m CMD authelia-health

ENTRYPOINT [ "authelia-entrypoint" ]
CMD        [ "authelia-run" ]
