---
name: Build and Push Images
on:
  push:
    branches: [main]

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  AUTHELIA_VERSION: 4.39.20
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v4

      - name: Build Authelia
        id: build-authelia
        uses: redhat-actions/buildah-build@v2
        with:
          image: authelia
          context: authelia
          containerfiles: authelia/Containerfile
          build-args: VERSION=${{ env.AUTHELIA_VERSION }}
          tags: latest git-${{ github.sha }} ${{ env.AUTHELIA_VERSION }}

      - name: Push To GHCR
        id: push-authelia
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-authelia.outputs.image }}
          tags: ${{ steps.build-authelia.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: --disable-content-trust

      - name: Print Image URL
        run: echo "Pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
