ARG VERSION

FROM docker.io/library/caddy:${VERSION:+${VERSION}-}builder AS builder

RUN echo xcaddy build --with github.com/caddy-dns/loopia > /usr/bin/caddy

FROM docker.io/library/caddy:${VERSION:-latest}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
